### PR TITLE
fix: Show correct cursor in footer and add mastodon

### LINKED ISSUE #1978: Add Mastodon link
https://staging.www.jabref.org/

image

Add Mastodon linked to https://foojay.social/@jabref

### LINKED ISSUE #2010: Mouse cursor shows text cursor instead of hand symbol
My screenshot app does not show the mouse cursor.
Occurs when hovering 'Legal notice' and 'Privacy policy'
grafik

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #2010
Fixes #1978

Follow up from #2181

### CODE REVIEW

**Comment by tobiasdiez** [comment]
The cursor doesn't seem to be fixed in the production (at least on firefox windows). Maybe just add a cursor style instead of the href hack? https://tailwindcss.com/docs/cursor#setting-the-cursor-style

**Comment by Siedlerchr** [comment]
the last time I did this it worked fine

**Comment by Siedlerchr** [comment]
grafik


when I edit in web inspector and change it to href = "" then it displays fine.
So it must be something else which is interfering here with the styles

**Comment by tobiasdiez** [comment]
Closing as this seems to be stale. Feel free to reopen, once you found a working fix (maybe as suggested above https://github.com/JabRef/JabRefOnline/pull/2226#issuecomment-1709513844)

**Pull request closed without merging**
