### PR TITLE
fix: fix cursor of some footer links and replace twitter with mastodon

### LINKED ISSUE #1978: Add Mastodon link
https://staging.www.jabref.org/

image

Add Mastodon linked to https://foojay.social/@jabref

### LINKED ISSUE #2010: Mouse cursor shows text cursor instead of hand symbol
My screenshot app does not show the mouse cursor.
Occurs when hovering 'Legal notice' and 'Privacy policy'
grafik

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #2010 
Fixes #1978

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Nice workaround (if this indeed fixes the cursor issue)!

Prettier is complaining though

**Comment by Siedlerchr** [comment]
I did not touch the other files the linter is complaining about They were failing before. I tested this with Firefox inspector.

**Comment by Siedlerchr** [comment]
I fixed the f*cking deployment by switching to ubuntu and you now force pushed all the changes! Are you serious?

**Comment by Siedlerchr** [comment]
I fixed the vue file. I didn't touch the other files and have no idea of this any types there

**Comment by tobiasdiez** [comment]
Thanks but the linter is still falling. Also the changes outside the footer file shouldn't be there, right?

**Pull request closed without merging**
